name: Build
on:
  push:
    branches:
    - '*'
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    tags-ignore:
    - '*.*'
  pull_request:
    types: [opened, reopened]
permissions: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.22.1
        id: go

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Build
        env:
          GIT_COMMIT: "${{ github.sha }}"
        run: |
          make vendors
          make build
